#端口号 项目名  jsp 热部署
server:
  port: 8081
  servlet:
    context-path:
    jsp:
      init-parameters:
        development: true

#连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bzmall?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #配置jackson
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  #虚拟目录
  resources:
    static-locations: file:f:\\fuwuqi
  servlet:
    multipart:
      #单个文件的最大值
      max-file-size: 10MB
      #单次请求最大值
      max-request-size: 10MB
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.park.entity

#分页
pagehelper:
  helperDialect: mysql

